### ISSUE TITLE
Add missing media types

### ISSUE THREAD

**Issue by lfades** [lfades/static-tweet#12]
With the [new HTML API](https://github.com/lfades/static-tweet/pull/11), some media types are currently not working:

- [ ] Video streaming
- [ ] GIFs
- [ ] Polls

**Comment by DaniGuardiola** [comment]
Hi @lfades :)

What is the status of this? Can I help?

Also, unrelated question, is there any intention to ship an "official" npm module? Could I publish my own based on this module, or could I help make it happen?

**Comment by lfades** [comment]
@DaniGuardiola The project is licensed under MIT and you are welcome to publish your own module!

I'm currently not working on this improvements and don't have a timeline for it.

**Comment by DaniGuardiola** [comment]
@lfades Thank you, that's great! Mind to give me a quick briefing on the state of the project, so I can keep working from where you left it off?

**Comment by lfades** [comment]
@DaniGuardiola It's a simple Next.js app with some JSX and styles using styled-jsx and CSS modules.

The API code to get the data relies on the API that Twitter uses for their embedded tweets in external sites, I basically make the same request and use the data it returns (it's not documented anywhere). Then using `getStaticProps` I return that data as a JSON and transform it into JSX using some loops.

**Comment by DaniGuardiola** [comment]
@lfades that makes sense, thanks a lot!

**Comment by fajarsiddiqfs** [comment]
Thanks man!

**Comment by lfades** [comment]
I've released a new package that will be taking care of the features used here: https://github.com/lfades/next-tweet

It's aiming to be a 1:1 match to Twitter's official embedded tweets.
