### ISSUE TITLE
Question regarding the "Syndication" API

### ISSUE THREAD

**Issue by siffogh** [lfades/static-tweet#19]
First of all, thanks a lot for this amazing codebase ❤️.

I managed to reuse it for my own application but had some doubts regarding the API you use to fetch the HTML of tweets: `https://syndication.twitter.com`.

Is this a reliable source? Is it documented anywhere?

**Comment by pbshgthm** [comment]
I talked to someone from twitter and was informed that this is an internal endpoint used by the twitter products. It's not guaranteed that the endpoint and specification will remain constant over time and might be changed without any notice and hence is not a reliable way of getting tweer data. The best way is to use their API to get all the data related to the tweets.

**Comment by lfades** [comment]
Some notes on this, the data provided by their API at the time of writing the package was poor compared to using their internal endpoints. And their API keys have some limits that would have made the demo get rate limited quickly. Twitter also requires you to wait while they evaluate if you should have an API key or not, so for an OSS project that would have made things more complicated.

I'll be re-evaluating the API very soon and checking on this, so don't take my words as final, if you do have an API key you should be using it.
