### ISSUE TITLE
Render cropped previews of images with spacing inbetween instead of full image

### ISSUE THREAD

**Issue by RahmanQureshi** [lfades/static-tweet#27]
If an image is particularly long, the tweet will extend the entire length of the image.

Example: https://static-tweet.vercel.app/1415394850338443265

Enhancement request to add an option to render just the cropped previews.

**Comment by RahmanQureshi** [comment]
Here is another example that looks kinda ugly: https://static-tweet.vercel.app/1415391730996703232 due to no gap between the images

**Comment by lfades** [comment]
The layout for the tweets has been updated and this issue shouldn't apply anymore 👍
