### ISSUE TITLE
The layout of the tweet is misaligned

### ISSUE THREAD

**Issue by vsnthdev** [lfades/static-tweet#63]
### 🐛 What happens

New lines don't appear where they should & link breaks in the actual tweet are missed sometimes. An example tweet renders the following way 👇

![problem](https://user-images.githubusercontent.com/24322511/159337482-d47591c1-7f82-4956-818b-06cef55d5b40.jpg)

The above screenshot has been taken from 👉 https://static-tweet.vercel.app/1492115234936532992

Using the [react-static-tweets](https://www.npmjs.com/package/react-static-tweets) library, I have rendered the same tweet on my personal project, and it also suffers with the same problem 👇

![second problem](https://user-images.githubusercontent.com/24322511/159337954-ccd96f7e-a879-428d-8741-4e75199619a1.jpg)

### ✅ What should happen

The tweet should render with the correct line breaks, like so 👇

![correct](https://user-images.githubusercontent.com/24322511/159338197-7285fefa-245e-4592-83d4-505005f65943.jpg)

### ↪️ Steps to reproduce

1. Create a new directory & `cd` into it
2. Create a new Next.js project using `npx create-next-app@latest --ts`
3. Use the `Tweet` component with the [following tweet](https://twitter.com/vsnthdev/status/1492115234936532992).

### 🧐 My Observations

The issues seems to be with the styling of the twitter cards. This should be easily fixable with some CSS tinkering.

### ℹ️ Information

1. **Node.js** v14.19.1
2. **npm** v6.14.16
3. **Next.js** v12.1.0
4. **React** v17.0.2
5. **TypeScript** v4.6.2
6. **Operating System** Windows 11 (Version 21H2 Build 22000.556)

Happy to provide more information 😊

**Comment by vsnthdev** [comment]
### ✂️ Hotfix workaround

I have analyzed the markup being generated & came up with some hotfix JavaScript that fixes the alignment issues and renders the tweets properly.

Here's the code 👇

```javascript
document.querySelectorAll('.fixTweetRenderingProblems .static-tweet-p')
    .forEach(card => {
        let count = 0

        card.querySelectorAll('a').forEach(a => {
            if (a.textContent.startsWith('#')) {
                if (count == 0) {
                    a.innerHTML = `\n\n${a.innerHTML}`
                    card.parentElement?.parentElement?.parentElement?.classList.remove('fixTweetRenderingProblems')
                } else {
                    a.previousSibling.style.display = 'none'
                }

                count++
            }
        })
    })

document.querySelectorAll('.fixTweetRenderingProblems .static-tweet-p')
    .forEach(card => {
        const emojis = Array.from(card.querySelectorAll('.static-tweet-emoji'))

        for (const emoji of emojis) {
            if (Boolean(emoji.nextElementSibling) == false) continue
            if (emoji.nextElementSibling?.tagName.toLowerCase() == 'br') {
                const furtherNext = emoji.nextElementSibling.nextElementSibling

                if (Boolean(furtherNext) == false) return
                if (furtherNext?.tagName.toLowerCase() == 'a') {
                    emoji.nextElementSibling.style.display = 'none'
                }
            }
        }
    })
```

The first loop basically loops through all the extra `<br>` tags and disables them to fix extra new lines.

The second loop goes through a situation where "emoji, followed by a `<br>`, followed by an anchor link". In this particular case, it disables the `<br>` tag in between to fix the issue.

Although I **do not** recommend anyone use this workaround in production, I am posting this here to allow people to tinker with it, and implement a CSS only solution.

**Comment by lfades** [comment]
The Layout has been migrated to the new Twitter Embed layout so this issue should be fixed now!

**Comment by vsnthdev** [comment]
Thank you!
