### ISSUE TITLE
Seems a bit unstable / A lot of the tweets return 404

### ISSUE THREAD

**Issue by xd-hearst** [lfades/static-tweet#64]
The syndication.twitter.com seems a bit unstable. 

Tried a series of random tweets, most of them return 404 at the time of testing

https://static-tweet.vercel.app/1516967689478193154
https://static-tweet.vercel.app/1516967730053885955
https://static-tweet.vercel.app/1516967730053885955

**Comment by theopomies** [comment]
It seems it returns 404 while generating, then if you refresh, since it has been cached, it serves it correctly.
This is clearly a bug

**Comment by xd-hearst** [comment]
i have repeatedly tried to get data from the syndication api, 99% of the time it returns 404. The cached data is often stale and does not have all of the data points present in in a live twitter embed.  

Just FYI. It is certainly an interesting experiment, however not production ready

**Comment by lfades** [comment]
The syndication API that returned HTML has been replaced with one that returns JSON and is the one used by Twitter's official embedded tweets.
