### ISSUE TITLE
Twitter Syndication API changes broke this package

### ISSUE THREAD

**Issue by seeARMS** [lfades/static-tweet#66]
Twitter recently changed their syndication API. Now, this package seems to no longer work - fetching tweets are just returning 404s.

Similar to https://github.com/transitive-bullshit/react-static-tweets/issues/55.

ref: https://twitter.com/TwitterDev/status/1615405842735714304

**Comment by lfades** [comment]
I'm actively working on a lot of improvements and it will include the fix for this 👍 

btw I'm not affiliated in any way to that other repo.

**Comment by lfades** [comment]
This should be fixed now!
