### ISSUE TITLE
Question on deployment to vercel

### ISSUE THREAD

**Issue by MohammedAlrozzi** [lfades/static-tweet#71]
How can I create a copy of this cool feature - I tried and failed to fork and deploy to vercel. I wanted to add all my bookmarked twitter tweets so that I don't lose them even if I am migrating from twitter or if the tweets are deleted. I'll appreciate your advice to a beginner.

**Comment by lfades** [comment]
Hi @MohammedAlrozzi. You should be able to have your own tweets properly by using https://react-tweet.vercel.app/ (the predecessor of static-tweet)

To save tweets even if they're removed from twitter, I recommend using the [`getTweet`](https://react-tweet.vercel.app/api-reference#gettweet) function to save your tweets to your file system and then use that data to render tweets.
